services:
  telepark-frontend:
    build:
      context: .
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    ports:
      - "${PORT}:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:80"]
      interval: 30s
      timeout: 3s
      start_period: 10s
      retries: 3
    restart: unless-stopped
